defaults:
  - submitit_slurm
signal_delay_s: 120
timeout_min: 2880
partition: kate_reserved
gres: gpu:1
cpus_per_task: 8
mem_gb: 42
nodes: 1
constraint: 6000ADA # |rtx6000|rtx2080ti|rtx3080|A6000
max_num_timeout: 100
exclude: matrix-0-18,matrix-0-16,matrix-0-22,matrix-0-36,matrix-1-22
submitit_folder: out_slurm
name: inverse
